### ISSUE TITLE
Exclude proto files from crates release

### ISSUE THREAD

**Issue by andygrove** [substrait-io/substrait-rs#44]
We should not require downstream crates to have `protoc` installed, therefore we should exclude the `.proto` files from the crates release and only have `build.rs` build the proto files if they are present.

Here is a PR from DataFusion that implemented this: https://github.com/apache/arrow-datafusion/pull/3950

**Comment by mbrobbel** [comment]
I'm -1 on checking in generated code because it's easy to grab a `protoc` binary from https://github.com/protocolbuffers/protobuf/releases, and we can provide a fallback (behind a feature-flag) to build `protoc` from source via https://docs.rs/prost-build/latest/prost_build/#compiling-protoc-from-source.

**Comment by andygrove** [comment]
I'm running into this issue again, this time with a Python package that uses DataFusion.

It seems unusual to require people to install protoc just to install a Python package?

https://github.com/andygrove/ray-sql/issues/20

**Comment by mbrobbel** [comment]
I'm no expert on python packaging but instead of building on install you should be able to package everything (including dependencies) in a wheel. You can use [maturin](https://www.maturin.rs/distribution.html#build-wheels) to build these and then publish them as assets for releases with https://github.com/PyO3/maturin-action.

If these wheels are published to pip, and someone tries to install from a platform for which you didn't publish the wheels they could go and build from source, and in that case I think it's fine to require a protobuf compiler.

**Comment by andygrove** [comment]
Thanks @mbrobbel. That makes sense. I went ahead and published a wheel, and that works well. I'll close this issue.
